[package]
name = "ajour"
description = "A World of Warcraft addon manager"
version = "0.3.4"
authors = ["Casper Rogild Storm"]
license = "MIT"
homepage = "https://github.com/casperstorm/ajour"
repository = "https://github.com/casperstorm/ajour"
readme = "README.md"
keywords = ["addon-manager", "wow", "world-of-warcraft", "addon"]
categories = ["graphics", "gui", "games"]
edition = "2018"
default-run = "ajour"

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", features = ["debug"], rev = "fb015a85d22a7c4632bd251127a89259bfd0c346" }
iced_futures = { git = "https://github.com/hecrj/iced.git", features = ["async-std"], rev = "fb015a85d22a7c4632bd251127a89259bfd0c346" }
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "fb015a85d22a7c4632bd251127a89259bfd0c346" }
regex = "1.3.9"
fancy-regex = "0.3.5" # Regex with backtracking
async-std = "1.6.2"
dirs = "3.0"
serde = "1.0.114"
serde_yaml = "0.8.13"
serde_derive = "1.0.114"
serde_json = "1.0.57"
isahc = { version = "0.9.6", features = ["json"] }
zip = "0.5.6"
percent-encoding = "2.1.0"
image = "0.23.8"
native-dialog = "0.4.2"
opener = "0.4.1"
glob = "0.3.0"
rayon = "1.4.0"
lazy_static = "1.4.0"
chrono = "0.4"
log = "0.4"
fern = "0.6"
timeago = "0.2.1"
walkdir = "2.3"

widgets = { path = "crates/widgets" }

[build-dependencies]
embed-resource = "1.3.3"

[workspace]
members = [
    ".",
    "crates/widgets"
]
