[package]
name = "ajour"
description = "A World of Warcraft addon manager"
version = "0.1.0-beta5"
authors = ["Casper Rogild Storm"]
license = "MIT"
homepage = "https://github.com/casperstorm/ajour"
edition = "2018"

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git", features = ["debug"], rev = "2ce5df084456a92ed1a228738816cf8398b2e918" }
iced_futures = { git = "https://github.com/hecrj/iced.git", features = ["async-std"], rev = "2ce5df084456a92ed1a228738816cf8398b2e918" }
walkdir = "2.3.1"
regex = "1.3.9"
async-std = "1.6.2"
dirs = "3.0"
serde = "1.0.114"
serde_yaml = "0.8.13"
serde_derive = "1.0.114"
serde_json = "1.0.57"
isahc = { version = "0.9.6", features = ["json"] }
zip = "0.5.6"
percent-encoding = "2.1.0"

[build-dependencies]
embed-resource = "1.3.3"
