[package]
name = "ajour"
version = "0.1.0"
authors = ["Casper Rogild Storm", "Kasper Kronborg"]
edition = "2018"

[dependencies]
iced = "0.1.1"
walkdir = "2.3.1"
regex = "1.3.9"
async-std = "1.6.2"
dirs = "3.0"
serde = "1.0.114"
serde_yaml = "0.8.13"
serde_derive = "1.0.114"
serde_json = "1.0.57"
isahc = { version = "0.9.6", features = ["json"] }
zip = "0.5.6"
