[package]
name = "ajour-widgets"
version = "0.5.4-rc.1"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[features]
wgpu = ["iced_wgpu"]
opengl = ["iced_glow"]

[dependencies]
iced_native = { version = "0.3" }
iced_graphics = { version = "0.1" }

iced_wgpu = { version = "0.3", optional = true }
iced_glow = { version = "0.1", optional = true }
