[package]
name = "widgets"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"


[dependencies]
iced_native = { git="https://github.com/hecrj/iced", rev="fb015a85d22a7c4632bd251127a89259bfd0c346" }
iced_wgpu = { git="https://github.com/hecrj/iced", rev="fb015a85d22a7c4632bd251127a89259bfd0c346" }
iced_graphics = { git="https://github.com/hecrj/iced", rev="fb015a85d22a7c4632bd251127a89259bfd0c346" }
