
name: "Release to Crates"

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Create release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_IO_TOKEN }}
    - name: switch working dir
      working-directory: ./crates/core
    - name: publish core
      uses: actions-rs/cargo@v1
      with:
        command: publish
    - name: wait 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: switch working dir
      working-directory: ./crates/widgets
    - name: publish widgets
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --features wgpu
    - name: wait 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: switch working dir
      working-directory: ./crates/weak_auras
    - name: publish weak_auras
      uses: actions-rs/cargo@v1
      with:
        command: publish
    - name: wait 5 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: publish main
      uses: actions-rs/cargo@v1
      with:
        command: publish
