name: Update terms
on: workflow_dispatch

jobs:
  update-terms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push terms to POEditor
        run: curl -X POST https://api.poeditor.com/v2/projects/upload
          -F api_token="${{ secrets.POEDITOR_API_TOKEN }}"
          -F id="${{ secrets.POEDITOR_ID_ADMIN }}"
          -F updating="terms"
          -F file=@"locale/en.json"
